Upload files to SharePoint
jalagari/franklin-submit-wrapper pull request #2
Opened 2023-05-31 08:11 UTC by jalagari

2023-05-31 11:51 UTC, tripodsan requested changes
- missing js doc
- wrong use of global variables
- not sure why FileUpload and SharePointFileUpload are 2 classes, as the first doesn't do anything

2023-05-31 11:51 UTC, tripodsan commented on src/index.js
> +    Util.FRANKLIN_UPLOAD_KV = env.FRANKLIN_UPLOAD_KV;
this is a bit ugly here... overwriting a global variable on every request....

2023-05-31 11:51 UTC, tripodsan commented on src/microsoft/MicrosoftGraphSharePoint.js
> +    createFolder = async(folderName) => {
why not use method syntax? (applies for all methods)

```suggestion
    sync createFolder(folderName) {
```

2023-05-31 11:51 UTC, tripodsan commented on src/microsoft/MicrosoftGraphSharePoint.js
> +        let content = {name: "dummy file"};
just curious: does this work? uploading an object?

2023-05-31 11:51 UTC, tripodsan commented on src/microsoft/OBOFAuthenticationProvider.js
> +        this.token = await Util.getCache()
this is not so nice:
- `Util` should not be static
- `Util` is a wrong name, if it only caches the token

2023-05-31 11:51 UTC, tripodsan commented on src/model/Util.js
> +    static getCache = async() => {
```suggestion
    static getCachedToken = async() => {
```

2023-05-31 11:51 UTC, tripodsan commented on src/model/Util.js
> +    static setCache = async (data) => await Util.FRANKLIN_UPLOAD_KV?.put('token', JSON.stringify(data))
- better name
- use method syntax!

```suggestion
    static sync cacheToken(data)  {
      await Util.FRANKLIN_UPLOAD_KV?.put('token', JSON.stringify(data));
     }
```

2023-05-31 11:51 UTC, tripodsan commented on src/upload/SharePointFileUpload.js
> +    sharePoint;
this one is a bit lonely :-) maybe add a jsdoc ?

2023-05-31 11:51 UTC, tripodsan commented on src/upload/SharePointFileUpload.js
> +    }
this is a bit dangerous...:
- the super classes method is not async but this one is
- the name suggest that the path is returned, but this also has the side effect of generating the folder. it would be better to separate the 2

2023-05-31 11:51 UTC, tripodsan commented on src/upload/SharePointFileUpload.js
> +}
same here. the super class doesn't really upload the file, so the name is misleading.

2023-05-31 12:05 UTC, solaris007 commented on src/microsoft/OBOFAuthenticationProvider.js
> +        console.log('Token Gen status', response.status, response.statusText)
Be careful where and how you're logging information. Logging the request to get a token can inadvertently expose sensitive data like the client secret, especially if the request fails. Make sure to log responsibly, and never log the client secret or access token.

2023-05-31 15:20 UTC, tripodsan commented on src/microsoft/OBOFAuthenticationProvider.js
> +    async #getToken(grantType= 'authorization_code', includInCache = true) {
typo: 
```suggestion
    async #getToken(grantType= 'authorization_code', includeInCache = true) {
```

2023-05-31 15:23 UTC, tripodsan commented on src/microsoft/OBOFAuthenticationProvider.js
> +            body: Util.getURLEncoded(data)
```suggestion
            body: new URLSearchParams(data).toString(),
```

2023-05-31 16:10 UTC, jalagari commented on src/microsoft/MicrosoftGraphSharePoint.js
> +            this.createFolder(folderName);
Yes, Forgot to remove the this line.
Line 89 is sufficient for executing actual.

2023-05-31 16:11 UTC, jalagari commented on src/microsoft/OBOFAuthenticationProvider.js
> +        console.log('Token Gen status', response.status, response.statusText)
statusText was added for testing.

2023-05-31 16:28 UTC, jalagari commented on src/microsoft/MicrosoftGraphSharePoint.js
> +        });
It was executing incase folderId is not provided in env variable

2023-06-01 05:39 UTC, tripodsan commented on src/microsoft/OBOFAuthenticationProvider.js
> +            if(includInCache) {
```suggestion
            if(includeInCache) {
```

2023-06-01 06:42 UTC, vdua commented on src/microsoft/MicrosoftGraphSharePoint.js
> +                '@microsoft.graph.conflictBehavior': 'rename'
isn't this param need to be included in the URL as per the [documentation](https://learn.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0#instance-attributes)

2023-06-01 12:59 UTC, jalagari commented on src/microsoft/MicrosoftGraphSharePoint.js
> +            console.log(`Uploading File with name ${fileName}`)
Sanitization happend in AbstractFile upload

2023-06-01 13:03 UTC, jalagari commented on src/microsoft/MicrosoftGraphSharePoint.js
> +                .put(content);
Last time I tried post it was working and document only specify about PUT.

For each submission different folder is created so there are no chances of replacing any existing file and client avoid adding same file twice.

2023-06-01 13:03 UTC, jalagari commented on src/microsoft/MicrosoftGraphSharePoint.js
> +        let content = {name: "dummy file"};
Yes, It does work. I have retested it again

2023-06-02 11:32 UTC, solaris007 approved these changes

2023-06-02 11:37 UTC, merged